# Generated by Django 3.1.3 on 2020-12-04 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='contact',
            name='notes',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Notes'),
        ),
    ]
