# Generated by Django 3.1.3 on 2020-12-04 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20201204_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='notes',
            field=models.TextField(blank=True, max_length=240, null=True, verbose_name='Notes'),
        ),
    ]
