# Generated by Django 3.1.3 on 2020-12-07 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_contact_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='location',
            field=models.CharField(choices=[('Argentina', 'Argentina'), ('Bolivia', 'Bolivia'), ('Brazil', 'Brazil'), ('Colombia', 'Colombia'), ('Costa Rica', 'Costa Rica'), ('Ecuador', 'Ecuador'), ('El Salvador', 'El Salvador'), ('Guatemala', 'Guatemala'), ('Honduras', 'Honduras'), ('Mexico', 'Mexico'), ('Nicaragua', 'Nicaragua'), ('Panama', 'Panama'), ('Paraguay', 'Paraguay'), ('Peru', 'Peru'), ('Spain', 'Spain'), ('Trinidad and Tobago', 'Trinidad and Tobago'), ('United States', 'United States'), ('Uruguay', 'Uruguay'), ('Venezuela', 'Venezuela')], help_text='Required', max_length=30, null=True, verbose_name='Country'),
        ),
    ]
