# Generated by Django 3.1.4 on 2020-12-23 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_auto_20201217_0026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['first_name']},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='notes',
        ),
        migrations.AddField(
            model_name='contact',
            name='source',
            field=models.CharField(choices=[('Account Contact', 'Account Contact'), ('Vendor Contact', 'Vendor Contact')], default='Account Contact', max_length=20, verbose_name='Source'),
        ),
    ]
