# Generated by Django 3.1.4 on 2020-12-24 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_auto_20201223_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['source']},
        ),
        migrations.AddField(
            model_name='contact',
            name='vendor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Vendor'),
        ),
    ]
