# Generated by Django 3.1.4 on 2021-01-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_auto_20201224_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_lead',
            field=models.BooleanField(default=False, verbose_name='Lead'),
        ),
    ]
