# Generated by Django 3.1.3 on 2020-12-02 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Name')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parent_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Name')),
                ('industry', models.CharField(blank=True, choices=[('ADVERTISING', 'Advertising'), ('AGRICULTURE', 'Agriculture'), ('APPAREL & ACCESSORIES', 'Apparel & Accesories'), ('AUTOMOTIVE', 'Automotive'), ('BANKING', 'Banking'), ('BIOTECHNOLOGY', 'Biotechnology'), ('BUILDING MATERIALS & EQUIPMENT', 'Building, Material & Equipment'), ('CHEMICAL', 'Chemical'), ('EDUCATION', 'Education'), ('ELECTRONICS', 'Electronics'), ('UTILITIES', 'Utilities'), ('OIL & GAS', 'Oil & Gas'), ('ENTERTAINMENT & LEISURE', 'Entertainment & Leisure'), ('FINANCE', 'Finance'), ('FOOD & BEVERAGE', 'Food & Beverage'), ('GROCERY', 'Grocery'), ('HEALTHCARE', 'Healthcare'), ('INSURANCE', 'Insurance'), ('LEGAL', 'Legal'), ('MANUFACTURING', 'Manufacturing'), ('PUBLISHING', 'Publishing'), ('REAL ESTATE', 'Real State'), ('SERVICE', 'Service'), ('SOFTWARE', 'Software'), ('SPORTS', 'Sports'), ('TECHNOLOGY', 'Technology'), ('TELECOMMUNICATIONS', 'Telecommunications'), ('TRANSPORTATION', 'Transportation'), ('OTHER', 'Other')], max_length=255, null=True, verbose_name='Industry Type')),
                ('category', models.CharField(blank=True, choices=[('Platinum', 'Platinum'), ('Gold', 'Gold'), ('Silver', 'Silver'), ('Bronce', 'Bronce')], max_length=10, null=True, verbose_name='Category')),
                ('slug', models.SlugField()),
                ('status', models.CharField(choices=[('Client', 'Client'), ('Prospect', 'Prospect'), ('Ex-Client', 'Ex-Client')], max_length=10, verbose_name='Status')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('country', models.CharField(blank=True, choices=[('AR', 'Argentina'), ('BO', 'Bolivia'), ('BR', 'Brazil'), ('CO', 'Colombia'), ('CR', 'Costa Rica'), ('EC', 'Ecuador'), ('SV', 'El Salvador'), ('GT', 'Guatemala'), ('HN', 'Honduras'), ('MX', 'Mexico'), ('NI', 'Nicaragua'), ('PA', 'Panama'), ('PY', 'Paraguay'), ('PE', 'Peru'), ('ES', 'Spain'), ('TT', 'Trinidad and Tobago'), ('US', 'United States'), ('UY', 'Uruguay'), ('VE', 'Venezuela')], max_length=3, null=True)),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_assigned_user', to=settings.AUTH_USER_MODEL)),
                ('contacts', models.ManyToManyField(related_name='account_contacts', to='contacts.Contact')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_created_by', to=settings.AUTH_USER_MODEL)),
                ('parent_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_company', to='accounts.parentcompany')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
