# Generated by Django 3.1.3 on 2020-12-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('accounts', '0002_auto_20201202_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='account_contacts', to='contacts.Contact'),
        ),
    ]
