# Generated by Django 3.1.3 on 2020-12-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201202_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='category',
            field=models.CharField(choices=[('Platinum', 'Platinum'), ('Gold', 'Gold'), ('Silver', 'Silver'), ('Bronce', 'Bronce')], max_length=10, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='account',
            name='country',
            field=models.CharField(choices=[('AR', 'Argentina'), ('BO', 'Bolivia'), ('BR', 'Brazil'), ('CO', 'Colombia'), ('CR', 'Costa Rica'), ('EC', 'Ecuador'), ('SV', 'El Salvador'), ('GT', 'Guatemala'), ('HN', 'Honduras'), ('MX', 'Mexico'), ('NI', 'Nicaragua'), ('PA', 'Panama'), ('PY', 'Paraguay'), ('PE', 'Peru'), ('ES', 'Spain'), ('TT', 'Trinidad and Tobago'), ('US', 'United States'), ('UY', 'Uruguay'), ('VE', 'Venezuela')], max_length=3, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='account',
            name='industry',
            field=models.CharField(choices=[('ADVERTISING', 'Advertising'), ('AGRICULTURE', 'Agriculture'), ('APPAREL & ACCESSORIES', 'Apparel & Accesories'), ('AUTOMOTIVE', 'Automotive'), ('BANKING', 'Banking'), ('BIOTECHNOLOGY', 'Biotechnology'), ('BUILDING MATERIALS & EQUIPMENT', 'Building, Material & Equipment'), ('CHEMICAL', 'Chemical'), ('EDUCATION', 'Education'), ('ELECTRONICS', 'Electronics'), ('UTILITIES', 'Utilities'), ('OIL & GAS', 'Oil & Gas'), ('ENTERTAINMENT & LEISURE', 'Entertainment & Leisure'), ('FINANCE', 'Finance'), ('FOOD & BEVERAGE', 'Food & Beverage'), ('GROCERY', 'Grocery'), ('HEALTHCARE', 'Healthcare'), ('INSURANCE', 'Insurance'), ('LEGAL', 'Legal'), ('MANUFACTURING', 'Manufacturing'), ('PUBLISHING', 'Publishing'), ('REAL ESTATE', 'Real State'), ('SERVICE', 'Service'), ('SOFTWARE', 'Software'), ('SPORTS', 'Sports'), ('TECHNOLOGY', 'Technology'), ('TELECOMMUNICATIONS', 'Telecommunications'), ('TRANSPORTATION', 'Transportation'), ('OTHER', 'Other')], default=3, max_length=255, verbose_name='Industry Type'),
            preserve_default=False,
        ),
    ]
