# Generated by Django 3.1.3 on 2020-12-03 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201202_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='country',
            field=models.CharField(choices=[('Argentina', 'Argentina'), ('Bolivia', 'Bolivia'), ('Brazil', 'Brazil'), ('Colombia', 'Colombia'), ('Costa Rica', 'Costa Rica'), ('Ecuador', 'Ecuador'), ('El Salvador', 'El Salvador'), ('Guatemala', 'Guatemala'), ('Honduras', 'Honduras'), ('Mexico', 'Mexico'), ('Nicaragua', 'Nicaragua'), ('Panama', 'Panama'), ('Paraguay', 'Paraguay'), ('Peru', 'Peru'), ('Spain', 'Spain'), ('Trinidad and Tobago', 'Trinidad and Tobago'), ('United States', 'United States'), ('Uruguay', 'Uruguay'), ('Venezuela', 'Venezuela')], max_length=30, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='account',
            name='industry',
            field=models.CharField(choices=[('Advertising', 'Advertising'), ('Agriculture', 'Agriculture'), ('Apparel & Accesories', 'Apparel & Accesories'), ('Automotive', 'Automotive'), ('Banking', 'Banking'), ('Biotechnology', 'Biotechnology'), ('Building, Material & Equipment', 'Building, Material & Equipment'), ('Chemical', 'Chemical'), ('Education', 'Education'), ('Electronics', 'Electronics'), ('Utilities', 'Utilities'), ('Oil & Gas', 'Oil & Gas'), ('Entertainment & Leisure', 'Entertainment & Leisure'), ('Finance', 'Finance'), ('Food & Beverage', 'Food & Beverage'), ('Grocery', 'Grocery'), ('Healthcare', 'Healthcare'), ('Insurance', 'Insurance'), ('Legal', 'Legal'), ('Manufacturing', 'Manufacturing'), ('Publishing', 'Publishing'), ('Real State', 'Real State'), ('Service', 'Service'), ('Sports', 'Sports'), ('Technology', 'Technology'), ('Telecommunications', 'Telecommunications'), ('Transportation', 'Transportation'), ('Other', 'Other')], max_length=255, verbose_name='Industry Type'),
        ),
    ]
