# Generated by Django 3.1.3 on 2020-12-04 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201202_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='category',
            field=models.CharField(choices=[('Platinum', 'Platinum'), ('Gold', 'Gold'), ('Silver', 'Silver'), ('Bronce', 'Bronce')], help_text='Required', max_length=10, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='account',
            name='country',
            field=models.CharField(choices=[('Argentina', 'Argentina'), ('Bolivia', 'Bolivia'), ('Brazil', 'Brazil'), ('Colombia', 'Colombia'), ('Costa Rica', 'Costa Rica'), ('Ecuador', 'Ecuador'), ('El Salvador', 'El Salvador'), ('Guatemala', 'Guatemala'), ('Honduras', 'Honduras'), ('Mexico', 'Mexico'), ('Nicaragua', 'Nicaragua'), ('Panama', 'Panama'), ('Paraguay', 'Paraguay'), ('Peru', 'Peru'), ('Spain', 'Spain'), ('Trinidad and Tobago', 'Trinidad and Tobago'), ('United States', 'United States'), ('Uruguay', 'Uruguay'), ('Venezuela', 'Venezuela')], help_text='Required', max_length=30, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='account',
            name='industry',
            field=models.CharField(choices=[('Advertising', 'Advertising'), ('Agriculture', 'Agriculture'), ('Apparel & Accesories', 'Apparel & Accesories'), ('Automotive', 'Automotive'), ('Banking', 'Banking'), ('Biotechnology', 'Biotechnology'), ('Building, Material & Equipment', 'Building, Material & Equipment'), ('Chemical', 'Chemical'), ('Education', 'Education'), ('Electronics', 'Electronics'), ('Utilities', 'Utilities'), ('Oil & Gas', 'Oil & Gas'), ('Entertainment & Leisure', 'Entertainment & Leisure'), ('Finance', 'Finance'), ('Food & Beverage', 'Food & Beverage'), ('Grocery', 'Grocery'), ('Healthcare', 'Healthcare'), ('Insurance', 'Insurance'), ('Legal', 'Legal'), ('Manufacturing', 'Manufacturing'), ('Publishing', 'Publishing'), ('Real State', 'Real State'), ('Service', 'Service'), ('Sports', 'Sports'), ('Technology', 'Technology'), ('Telecommunications', 'Telecommunications'), ('Transportation', 'Transportation'), ('Other', 'Other')], help_text='Required', max_length=255, verbose_name='Industry Type'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(help_text='Required', max_length=64, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='parent_company',
            field=models.ForeignKey(help_text='Required', on_delete=django.db.models.deletion.CASCADE, related_name='parent_company', to='accounts.parentcompany'),
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('Client', 'Client'), ('Prospect', 'Prospect'), ('Ex-Client', 'Ex-Client')], default='Prospect', help_text='Required', max_length=10, verbose_name='Status'),
        ),
    ]
