# Generated by Django 3.1.3 on 2020-12-06 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20201206_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentcompany',
            name='category',
            field=models.CharField(choices=[('Platinum', 'Platinum'), ('Gold', 'Gold'), ('Silver', 'Silver'), ('Bronce', 'Bronce')], help_text='Required', max_length=10, verbose_name='Category'),
        ),
    ]
