# Generated by Django 3.1.4 on 2020-12-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_account_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentcompany',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
    ]
