# Generated by Django 3.1.4 on 2020-12-17 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20201217_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentcompany',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
