# Generated by Django 3.1.4 on 2020-12-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_parentcompany_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentcompany',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
