# Generated by Django 3.1.4 on 2020-12-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_auto_20201224_0009'),
        ('accounts', '0015_auto_20201217_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='contacts',
            field=models.ManyToManyField(related_name='account_contacts', to='contacts.Contact'),
        ),
    ]
