# Generated by Django 3.1.4 on 2020-12-30 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20201228_2335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parentcompany',
            options={'ordering': ['name'], 'verbose_name_plural': 'Parent Conmpanies'},
        ),
    ]
