# Generated by Django 3.1.4 on 2021-01-04 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20201230_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='parent_company',
            field=models.ForeignKey(help_text='Required', on_delete=django.db.models.deletion.PROTECT, related_name='account_parent_company', to='accounts.parentcompany'),
        ),
    ]
