# Generated by Django 3.1.4 on 2021-01-16 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20210116_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='parent_company',
        ),
        migrations.AddField(
            model_name='account',
            name='parent_account',
            field=models.ForeignKey(default=1, help_text='Required', on_delete=django.db.models.deletion.PROTECT, related_name='account_parent_account', to='accounts.parentaccount'),
            preserve_default=False,
        ),
    ]
