# Generated by Django 3.1.4 on 2021-05-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20210116_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentaccount',
            name='category',
            field=models.CharField(blank=True, choices=[('Platinum', 'Platinum'), ('Gold', 'Gold'), ('Silver', 'Silver'), ('Bronce', 'Bronce')], help_text='Required', max_length=10, verbose_name='Category'),
        ),
    ]
