# Generated by Django 3.1.4 on 2021-05-01 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20210501_1238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parentaccount',
            options={'ordering': ['name'], 'verbose_name_plural': 'Parent Accounts'},
        ),
    ]
