# Generated by Django 3.1.4 on 2021-05-02 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20210501_1245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parentaccount',
            options={'ordering': ['name'], 'verbose_name': 'Parent Account', 'verbose_name_plural': 'Parent Accounts'},
        ),
    ]
