# Generated by Django 3.1.4 on 2020-12-29 23:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0005_auto_20201229_2004'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='note',
            name='title',
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('Call', 'Call'), ('Meet', 'Meet'), ('Task', 'Task'), ('Email', 'Email'), ('Launch', 'Launch')], default='Call', max_length=10, verbose_name='Type of Activity'),
        ),
        migrations.AddField(
            model_name='activity',
            name='body',
            field=tinymce.models.HTMLField(null=True, verbose_name='Note'),
        ),
        migrations.AddField(
            model_name='activity',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created on'),
        ),
        migrations.AddField(
            model_name='activity',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='date',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='activity',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Done'),
        ),
        migrations.AddField(
            model_name='activity',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_opportunity', to='opportunities.opportunity'),
        ),
        migrations.AddField(
            model_name='activity',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='activity',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated on'),
        ),
    ]
