# Generated by Django 3.1.4 on 2020-12-29 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opportunities', '0005_auto_20201229_2004'),
        ('tasks', '0004_auto_20201229_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('Call', 'Call'), ('Meet', 'Meet'), ('Task', 'Task'), ('Email', 'Email'), ('Launch', 'Launch')], max_length=10, verbose_name='Type of Activity'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='body',
            field=tinymce.models.HTMLField(verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_created_by', to='core.user'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_opportunity', to='opportunities.opportunity'),
        ),
    ]
