# Generated by Django 3.1.3 on 2020-12-03 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='stage',
            field=models.CharField(choices=[('Identification', 'IDENTIFICATION'), ('In Contact', 'IN CONTACT'), ('Under Analysis', 'UNDER ANALYSIS'), ('Price Quote', 'PRICE QUOTE'), ('Negotiation/Review', 'NEGOTIATION/REVIEW'), ('Closed Won', 'CLOSED WON'), ('Colsed Lost', 'CLOSED LOST')], max_length=64, verbose_name='Stage'),
        ),
    ]
