# Generated by Django 3.1.4 on 2020-12-29 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0002_auto_20201202_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='date_of_funding',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='probability',
        ),
    ]
