# Generated by Django 3.1.4 on 2020-12-29 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_auto_20201224_0009'),
        ('opportunities', '0004_auto_20201229_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='contacts',
            field=models.ManyToManyField(related_name='opportunity_contacts', to='contacts.Contact'),
        ),
    ]
