# Generated by Django 3.1.4 on 2020-12-30 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0005_auto_20201229_2004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunity',
            options={'ordering': ['stage'], 'verbose_name_plural': 'Opportunities'},
        ),
        migrations.AddField(
            model_name='opportunity',
            name='date_of_funding',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Estimated Date of Funding'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Normal', 'Normal'), ('High', 'High'), ('Urgent', 'Urgent')], default='Low', max_length=6, verbose_name='Priority'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Opportunity Expected Amount'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='stage',
            field=models.CharField(choices=[('Identification', 'Identification'), ('In Contact', 'In Contact'), ('Under Analysis', 'Under Analysis'), ('Price Quote', 'Price Quote'), ('Negotiation/Review', 'Negotiation/Review'), ('Closed Won', 'Closed Won'), ('Colsed Lost', 'Closee Lost')], max_length=64, verbose_name='Stage'),
        ),
    ]
