# Generated by Django 3.1.4 on 2021-01-02 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opportunities', '0010_opportunity_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='assigned_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='opportunity_assigned_user', to='core.user'),
            preserve_default=False,
        ),
    ]
