# Generated by Django 3.1.4 on 2021-01-04 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20210104_1930'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opportunities', '0013_auto_20210103_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_opportunities', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_user_opportunities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_by_opportunities', to=settings.AUTH_USER_MODEL),
        ),
    ]
