# Generated by Django 3.1.4 on 2021-01-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0015_auto_20210107_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='stage',
            field=models.CharField(choices=[('5 - Identification', 'Identification'), ('4 - In Contact', 'In Contact'), ('3 - Under Analysis', 'Under Analysis'), ('2 - Price Quote', 'Price Quote'), ('1 - Negotiation/Review', 'Negotiation/Review'), ('6 - Closed Won', 'Closed Won'), ('7 - Closed Lost', 'Closee Lost')], max_length=64, verbose_name='Stage'),
        ),
    ]
