# Generated by Django 3.1.4 on 2021-01-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0017_auto_20210108_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='stage',
            field=models.CharField(choices=[('5 - Identification', 'Identification'), ('4 - In Contact', 'In Contact'), ('3 - Under Analysis', 'Under Analysis'), ('2 - Price Quote', 'Price Quote'), ('1 - Negotiation/Review', 'Negotiation/Review'), ('6 - Closed Won', 'Closed Won'), ('7 - Closed Lost', 'Closed Lost')], max_length=64, verbose_name='Stage'),
        ),
    ]
